version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ~/.docker-conf/mongodb/data:/data/pep-msg
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pep-msg
      MONGO_INITDB_DATABASE: pep-msg
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pep-msg
      ME_CONFIG_MONGODB_URL: mongodb://root:pep-msg@mongo:27017/
